version: '3.8'
services:
  ray-head:
    image: rayproject/ray:latest
    command: ray start --head --dashboard-host 0.0.0.0
    ports:
      - "8265:8265"
      - "6379:6379"

  ray-worker:
    image: rayproject/ray:latest
    depends_on:
      - ray-head
    command: ray start --address=ray-head:6379

  trainer:
    build:
      context: .
    volumes:
      - ./data:/mnt/data
    command: python trainer/train.py
    depends_on:
      - ray-head

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/tmp
    depends_on:
      - trainer

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8501:8501"
