services:
  ray-head:
    build: .
    container_name: ray-head
    command: bash -c "
      ray start --head --port=6379 --dashboard-host=0.0.0.0  --dashboard-port=8265 &&
      echo 'Nodo HEAD en marcha y escuchando en puertos 6379 y 8265' &&
      tail -f /dev/null"
    ports:
      - "6379:6379"   
      - "8265:8265"  
    networks:
      - ray-net
    shm_size: 1gb
    cpus: 2
    volumes:
      - .:/app
    
  ray-worker-1:
    build: .
    container_name: ray-worker-1
    command: bash -c "
      ray start --address=ray-head:6379 &&
      echo 'Worker 1 conectado al HEAD' &&
      tail -f /dev/null"
    depends_on:
      - ray-head
    networks:
      - ray-net
    shm_size: 1gb
    cpus: 1
    volumes:
      - .:/app

  ray-worker-2:
    build: .
    container_name: ray-worker-2
    command:  bash -c "
      ray start --address=ray-head:6379 &&
      echo 'Worker 2 conectado al HEAD' &&
      tail -f /dev/null"
    depends_on:
      - ray-head
    networks:
      - ray-net
    shm_size: 1gb
    cpus: 1
    volumes:
      - .:/app

  model-api:
    build: .
    container_name: model-api
    command:  python serve.py
    ports:
      - "8000:8000"
    depends_on:
      - ray-head
    networks:
      - ray-net
    volumes:
      - .:/app

  streamlit-app:
    build: .
    container_name: streamlit-app
    command: bash -c "streamlit run monitoring.py --server.address=0.0.0.0 --server.port=8501"
    depends_on:
      - ray-head
      - model-api
    ports:
      - "8501:8501"
    networks:
      - ray-net
    volumes:
      - .:/app

networks:
  ray-net:

