version: '3'
services:
  entrenamiento:
    build: ./training
    container_name: training_container
    command: ["python", "train.py"]
    volumes:
      - ./training/data:/app/data
    depends_on:
      - api
  
  api:
    build: ./api
    container_name: api_container
    ports:
      - "5000:5000"
    depends_on:
      - entrenamiento
